// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNL2VZZhOalybxx_0aXi15te-3Nl0dZo',
    appId: '1:922449730983:web:3d3f49a4dd89782109aa82',
    messagingSenderId: '922449730983',
    projectId: 'fir-flutter-bf8d7',
    authDomain: 'fir-flutter-bf8d7.firebaseapp.com',
    storageBucket: 'fir-flutter-bf8d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuroHjz9rFLWzuukGe0lbKwmu8taRfi6Q',
    appId: '1:922449730983:android:5b75e4e27330be1309aa82',
    messagingSenderId: '922449730983',
    projectId: 'fir-flutter-bf8d7',
    storageBucket: 'fir-flutter-bf8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoPcBUz5anlVfjjknqVjFTv01RZ8xnpLE',
    appId: '1:922449730983:ios:5092c6bfc449cfe309aa82',
    messagingSenderId: '922449730983',
    projectId: 'fir-flutter-bf8d7',
    storageBucket: 'fir-flutter-bf8d7.appspot.com',
    iosBundleId: 'com.huzaifi.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoPcBUz5anlVfjjknqVjFTv01RZ8xnpLE',
    appId: '1:922449730983:ios:0fdce07ca6b25d1309aa82',
    messagingSenderId: '922449730983',
    projectId: 'fir-flutter-bf8d7',
    storageBucket: 'fir-flutter-bf8d7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
